parameters:
    woecifaun.translationBridge.appLocales: [fr, en]

services:
    woecifaun_translation_bridge.view.listener:
        class: Woecifaun\Bundle\TranslationBridgeBundle\EventListener\TranslationBridgeListener
        arguments: [@router, %woecifaun.translationBridge.appLocales%]
        tags:
           - { name: kernel.event_subscriber }
