parameters:
    woecifaun_translation_bridge.class: Woecifaun\Bundle\TranslationBridgeBundle\Model\TranslationBridge

services:
    woecifaun_translation_bridge.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor
        arguments: [true, false]

    woecifaun_translation_bridge:
        class: %woecifaun_translation_bridge.class%
        arguments:
            - @router
            - @woecifaun_translation_bridge.property_accessor
            - %woecifaun.translationBridge.appLocales%

    woecifaun_translation_bridge.event_subscriber:
        class: Woecifaun\Bundle\TranslationBridgeBundle\EventListener\TranslationBridgeListener
        arguments:
            - @woecifaun_translation_bridge
        tags:
           - { name: kernel.event_subscriber }
