<?php

namespace Woecifaun\Bundle\TranslationBridgeBundle\Exception;

/**
 * Exception thrown when Translation Bridge
 * cannot find matching controller parameter
 */
class ParamNotFoundException extends Exception
{
    /**
     * Construct
     * @param string $paramName name of the invalid param
     * @param string $route route identifier
     */
    public function __construct($paramName, $route)
    {
        $message = <<<'EOD'
        Param "%s" not found for the route "%s".
        Either there's a typo in the TranslationBridge Annotation or the parameter "%s" is not generated by any ParamConverter. You can check that the priority defined for your ParamConverters is above the one for the TranslationBridgeListener (-64).
EOD;

        $message = sprintf($message, $paramName, $route, $paramName);

        parent::__construct($message);
    }
}
